### ISSUE TITLE
Game glitches cause corrupted save files

### ISSUE THREAD

**Issue by Kilg0reTr0ut** [hankmorgan/UnderworldExporter#16] opened 2017-12-19 23:33 UTC
Hank, I would LOVE to get in touch with you. I have been doing a playthrough of Ultima Underworld using your Unity port, and I have had issues where all my save games end up being corrupted. I've had this happen a couple times, usually after a graphical issue. For instance, I was using a fly potion, had moved up, but couldn't move forward or backwards. None of my saves would load then.

Any ideas?

**Comment by Kilg0reTr0ut** [comment] 2018-01-12 01:35
I'm still waiting for a reply. Hank are you out there?

**Comment by Kilg0reTr0ut** [comment] 2018-01-16 01:25
Here are my saves from  UU1. Notice that Save 1 won't load at all. This is typically what happens when I have a save game issue. Also, If you load Save 4 and try moving forward through the level entrance, it takes two attempts to go through.
[Kilg0re UW saves.zip](https://github.com/hankmorgan/UnderworldExporter/files/1633359/Kilg0re.UW.saves.zip)

**Comment by hankmorgan** [comment] 2018-01-16 20:03
Issue is due to an infinite looping object reference chain in the save file due to opening a container on the ground (e.g. a barrel) and spilling it's contents on the game world without clearing the container reference to the spilled objects.

Fixed in next release which I will upload once I have tested some more.

I've uploaded a partially repaired save file. Note that due to corruption in the level map file I've replaced the lev.ark file with one from another save game. Most objects and the automap are reset to an initial state but the character file and inventory is okay.

None of the save files (incl. the repaired file) will open in vanilla underworld so there may be other issues in the file that I cannot find.  Use at your own risk. 

[save1.zip](https://github.com/hankmorgan/UnderworldExporter/files/1636584/save1.zip)

**Comment by Kilg0reTr0ut** [comment] 2018-01-17 01:21
Looks ok so far!

**Comment by Kilg0reTr0ut** [comment] 2018-01-17 01:30
I just noticed that in 1.03 the graphics quality only shows "Fantastic" as an option. In game, it looks more like how "Fastest" looked in 1.02

**Comment by hankmorgan** [comment] 2018-01-18 23:15
Can't replicate here.  Have you extracted the game to a new folder?

**Comment by Kilg0reTr0ut** [comment] 2018-01-19 00:12
Hank, it still only shows Fantastic as a Graphic quality option in 1.03. When I run 1.02 it shows all the options.

**Comment by Kilg0reTr0ut** [comment] 2018-01-20 18:30
I meant Saturday night (as in tonight). I corrected the last comment

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 09:43
Having an issue with using the flying potion from in Save 3. Once I drink the potion the fly spell starts but my view screen goes black! Interestingly, when I go to an upper level across from this point and use the flying potion, it works fine. I can  use this second method and continue the game, but it would be good to get to the source of this error.
[Kilg0re UW saves (21-01-2018).zip](https://github.com/hankmorgan/UnderworldExporter/files/1649645/Kilg0re.UW.saves.21-01-2018.zip)

**Comment by hankmorgan** [comment] 2018-01-21 11:30
The vanilla save load issue is caused by something in your inventory. So far it appears to be related to items dropped by NPCs when you kill them. Dropping all your inventory on the ground and saving then allows you to load in UW vanilla.  So far I've identified 1 item in your inventory (the sling in the first bag) that is causing this but there are still a few more to find. I'll look at this issue later on today in detail

As for the flying glitch. I can't replicate in your save game. The only thing similar to that issue I'm aware of is when you die the game would re-spawn you in the wrong position. I notice you have the silver seed in your inventory so I'm guessing there might be something happening here with the seed and this respawn position and level variables. Do you have a time index on your stream so I can see what is happening exactly.

**Comment by hankmorgan** [comment] 2018-01-21 14:47
Attached is a fixed copy of your most recent save game. I've fixed the incorrect link values in your inventory and in maps objects spawned by dead npcs that are wrong. This file should open in vanilla without any issues. I'll be issuing an updated release in a couple of hours once I run through a few other items which will stop that inventory issue from breaking vanilla compatibility.

[save4.zip](https://github.com/hankmorgan/UnderworldExporter/files/1649830/save4.zip)

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 18:37
https://www.twitch.tv/videos/220740777
At 5:46, I find the potions. I Use the Fly potion and it works, so I reload the save and continue. at 5:55 I try the potion and the screen goes black. 
Around 6:06 I try these saves in the original Ultima game, where they crash.
At 6:19 I go to an area above and across from the area I need to fly to and the potion works fine here.

I can probably use this last method and continue the game. I will be streaming this game tonight as well at 10pmEST.

 I will check out the new save shortly as well and get back to you.

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 18:46
I tried 1.03c and the flying potion works fine now with my old saves.

Am i correct in assuming that there is no longer a Save0 folder needed? I see that the game folder I'm using with the Unity port doesn't have one.

**Comment by hankmorgan** [comment] 2018-01-21 20:32
That's weird. Can you you upload the glitched file again please?

I was watching a bit of your stream. The UI looks wrong in terms of positioning and size of elements. What resolution are you playing at as I could not replicate the issue at any resolution available to me?

Save0 is a used by vanilla UW1 as a cache at runtime. So it needs to be there and left alone. I think the game will create it if needed.

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 21:01
[Kilg0re UW saves (gargoyle) (21-01-2018).zip](https://github.com/hankmorgan/UnderworldExporter/files/1650200/Kilg0re.UW.saves.gargoyle.21-01-2018.zip)
here are the files again. Save 3 is a new save I did to test exporting to UW vanilla.
I'm running at 1600x1024 windowed. Btw, in this 1.03c build I have all teh graphic quality menu options again

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 21:08
AAAAh... I tried all the other resolutions. They look fine. 1600x1024 is the only one resolution that looks off.

**Comment by hankmorgan** [comment] 2018-01-21 21:33
Ok. I sent you back a fixed save file 4. On that file two of the items I fixed were sling stones at index 34 and 35 of the inventory list (inside a pouch in the first backpack) to give them a quality of 40 so they would stack properly. Loading your save 3 I can see that those fixed items have the same wrong quality value so I'm think the new save you made was based on a still broken save file and not the fixed file I sent you. As the issue was a data error release 1.03c does not fix the error if it was already present in a loaded save file.

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 21:46
Do you mean a new save4 or are you referring to the one you sent above?

**Comment by hankmorgan** [comment] 2018-01-21 21:49
The one I sent on earlier today.

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 21:51
k, I'm running that one right now. Flying works as I mentioned. You won't actually fly until you jump. Normally you just hit the fly controls and off you go.

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 21:58
Well, when I load the new save, I can fly, but again, I need to jump before the fly controls work. Then, if I restore the same save from within the game, I get the black screen when I drink the potion.

**Comment by hankmorgan** [comment] 2018-01-21 22:08
I know about the jump/flying issue. That's a long term bug with the character motor that I'm unable to fix so far.
Another thing that might be happening with the black screen bug is you might be clipping out of the game world. I can't replicate here though and I never had any other issues with the fly potion. Is there anything interesting about the location you are drinking the potion at. Are you at a low point in the map, near the ceiling, near a wall or object.

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 22:10
yes, I'm standing right below where the door is above. I can avoid the issue if I go to the higher ground across from where the path to the door is and fly straight across.

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 22:12
here's something i noticed. after I restore the game and drink potion and get black screen, when I exit and look at the files in that directory. the dates of the decod_4.dat and xor.dat have changed, as if theyve been overwritten. This shouldn't happen right? I haven't saved over them.

**Comment by hankmorgan** [comment] 2018-01-21 22:20
Thanks for all the feedback. I'll look into that position tomorrow

Don't worry about decode_4 and xor.dat. They don't affect anything. I use them to research save game formats. I had forgotten to turn off generation of those files when I released.

**Comment by Kilg0reTr0ut** [comment] 2018-01-21 22:26
K. I'll be streaming UW again tonight at 10pmEST. Other than these issues we've been discussing, the games been playing great and getting lots of reaction. The only other thing that comes to mind is the occasion looping sounds that randomly occur in some areas. One other request... it it possible to include a way to allow external audio programs like Virtual Midi Synth to be accessed? just a thought.

**Comment by Kilg0reTr0ut** [comment] 2018-01-22 09:37
The fly potion/black screen issue came up again, this time in a different spot on Level 3:
 https://www.twitch.tv/videos/221110259
Notice I fell in the water and couldn't jump, so I couldn't fly. I restored my save and again, the fly potion causes a black screen like before. After a restart, the save loaded fine, and the Fly potion worked. I'm including all my saves in case you need to look at them. Other than this, everything seemed to work fine.
[Kilg0re UW saves (22-01-2018).zip](https://github.com/hankmorgan/UnderworldExporter/files/1651447/Kilg0re.UW.saves.22-01-2018.zip)

One other feature someone asked for. Is it possible to add a map key? It would be handy instead of constantly having to click on the map to open it.

**Comment by hankmorgan** [comment] 2018-01-22 19:06
There is no midi in it at the moment. All music is pre-generated .ogg files I've included in the build.
I think what is happening is you are going out of bounds. It's not something that has happened to me once since I implemented flying so I'm going to review my code to see if there is anything I missed. I'll  also see if I can put in sanity checking to the player position to fix the issue if it they are go out of bounds.

**Comment by Kilg0reTr0ut** [comment] 2018-01-23 00:33
Sounds good. At least I know a restart solves the problem. Otherwise, the port works great!

**Comment by hankmorgan** [comment] 2018-02-13 22:39
Closing issue.

**Closed by hankmorgan** 2018-02-13 22:39 UTC

**Comment by fouriehs** [comment] 2019-10-22 15:28
Hi hank.

Same issue and few other. Can you help me?
