### ISSUE TITLE
Biden won't go home

### ISSUE THREAD

**Issue by Kilg0reTr0ut** [hankmorgan/UnderworldExporter#21] opened 2018-02-03 04:04 UTC
On Level 4, Biden is stuck and won't go home after I killed Sir Rodrick. It looks like his pathfinding is off and he's trying to walk through the wall.

**Comment by Kilg0reTr0ut** [comment] 2018-02-03 09:35
Here are the saves from my last session. Save 2 is right where Biden is stuck now. Also some other problems. 

I have the Gold Plate, but when I try to give it to Dorna, he says it's not the right one. 

I made the wormy stew for Sethar and he gives me the Dragon Scales and my weight goes to -1. If I then go to Dorna, even though I have given him the writ, and I have the Gold Plate, it seems the whole quest has reset and tests me and wants me to find the writ.

I tried loading the saves in Vanilla UW and they play for a minute and then UW freezes. I also noticed that even though my weight in Unity is like 1 or 2, my weight in Vanilla is 43

[UW Saves 1-4 (Biden-gold plate).zip](https://github.com/hankmorgan/UnderworldExporter/files/1691584/UW.Saves.1-4.Biden-gold.plate.zip)

**Comment by Shafticus** [comment] 2018-02-03 20:03
I had the same bugs in my games.  Biden gets stuck in a corener.  Gold plate not accepted for that quest.  Quest resets and general conversation issues.  For the weight, you might look at your inventory and look  for item that have been duplicated.  You might have a stack of 200+ sceptres or some other random item.  Though I would consider item duplication a separate issue from negative encumbrance from a programming perspective.  The number should never be negative for the purposes of the game.

**Comment by hankmorgan** [comment] 2018-02-03 20:58
I've also spotted a serious issue with the game data on level 4 (knights & trolls level). Basically the game has 1024 slots to store objects in the world. Usually in UW1 this is filled with junk objects that don't get loading. However on that level the game fills a lot of that space with a special object type that I always choose to load. This causes issues with newly spawned items and items you drop from your inventory. Although the object will appear properly in the world it has not slot in the main object list with causes issues with conversations and saving. I need to investigate this further. This might be the root cause of other issues with objects and conversations.

Path finding is not in a good state at the moment. 

I've identified the issue with the gold plate. Basically the game uses the objects OWNER value to identify the plate in the conversation. Due to the item stealing mechanic the game thinks you are stealing the plate when you pick it up and by design it clears the owner value to stop repeating the theft event.  I can fix in the next release but it will not apply retroactively for you. I can fix the save files in a couple of days but I noticed that the quest flags are not correct in the file. When I'm done fixing a few other issues I'll repair your save file and set the correct owner value on the plate and upload here.

**Comment by Zibit-Meowe** [comment] 2018-02-11 06:30
I'm also running into the issues listed above regarding Biden and especially the gold plate.

Unfortunately, in my oldest save, I have already picked up the item.  If you have a list of tools or how you are editing the saves, I'm sure I could compare a working save and edit the value.

I also ran into a bug on the same level when picking up single gold coins near Rodrick.  If the coins are added to a stack, the stack takes the image of a single coin no matter the number.  After a while... longer than the usual clicking in and out of bags lag... the weight of the stack jumps to something enormous and I am left at negative weight capacity.

I'm attaching the saves below.  Thanks so much for the awesome work you've done so far.  It makes me want to dig in and see how you've translated this to unity.

[MeoweSav.zip](https://github.com/hankmorgan/UnderworldExporter/files/1714086/MeoweSav.zip)

**Comment by Zibit-Meowe** [comment] 2018-02-11 17:35
I was able to write a little python snippet to XOR the player.dat file and now my character name is readable.  If you have a reference on how the file stores the inventory items, I'd greatly appreciate it.  I'm aware of the general structure, but the references I've found don't mention how the inventory items are structured.

I may have to rush down to the the plate bug on vanilla, drop everything except the plate, do the same in unity version, then compare and paste the corresponding unXor'd section into my save.  Might have to cheat my stats else it'd take as long as a new play through.  But your project has gotten me re-addicted to UW so I may just do that!

Thanks again!

**Comment by Zibit-Meowe** [comment] 2018-02-11 20:11
I was able to get the item by dropping all my items, making a save, then copying the player.dat.  I pasted a copy into the save directory of vanilla on a specific save.  In said save, I had rushed down, defeated Rodrick and retrieved the plate.  I had then dropped the plate in a known location and saved.  I backed up the vanilla player.dat, copied in the player.dat from UW Exporter, and loaded the save.  I grabbed the plate of the ground where I dropped it, saved, and then copied the player.dat file back.

I was able to turn in with no problems.  I'm still not sure why simply editing player.dat didn't work, but putting the same words into the inventory slot locations resulting in 'excellent leather gloves'. 

Hopefully this helps someone and the saves will be of use debugging.

**Comment by hankmorgan** [comment] 2018-02-11 21:09
Probably the best ways to edit inventory is to either load the save file in the dev environment or use the dos era save game edit (online search)

Inventory is actually stored in the same manner as the main game object list. Each object is about 8 bytes of info and is stored in a linked list. This info begins at offset 312d in the game file with the indices into the linked lists for each slot starting at offset 248d

Object list byte structure is covered in uwformats.txt and I'll upload my notes on the save file structure with my next code commit.

Let me know if you still want me to look at your save file.

**Comment by Zibit-Meowe** [comment] 2018-02-11 21:40
I totally missed the editor for saves.  I totally spaced out when I read about the editor;  I thought it was for testing map/layout chagnes in new game or quickstart.  Total reading fail.
Oh well, at least because of this I've become a lot more familiar with how UW stores its save data.
It serves me right for sitting up all night trying to make sense of an unknown file format until 3 AM.
Thanks for your help, if it won't inconvenience you too much, I would like a fixed copy of SAV 4.  I'll probably try fixing it myself through dev editor.  But just in case my 'fix' causes some problem later on, I'd at least have a known good location to keep playing/testing.
No rush.  Take care!

**Comment by hankmorgan** [comment] 2018-02-11 22:00
No problem.

Here is a fixed copy of save4. I've set the plate to have the correct owner and fixed a bunch of quest flags that it looks like you should have at this point.
[zibit-save4.zip](https://github.com/hankmorgan/UnderworldExporter/files/1714894/zibit-save4.zip)

**Comment by Zibit-Meowe** [comment] 2018-02-11 22:04
Thanks!  Even if Biden can't make it back, with that save I can at least play through the rest now and test some more things.  Maybe a routing fix at some point will allow him to finally make it around that sharp corner.

**Comment by hankmorgan** [comment] 2018-02-11 22:25
The release I'm uploading tonight will fix all the old ai bugs and create a bunch of new ones. But pathing in general should be working okay after that.

**Comment by hankmorgan** [comment] 2018-02-13 22:51
Closing this topic. In the latest release Biden now goes home and gives you the scroll he finds.

**Closed by hankmorgan** 2018-02-13 22:51 UTC
